version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - crypto-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      start_period: 5s
      interval: 10s
      timeout: 10s
      retries: 5

  crypto-app:
    build:
      context: crypto-app
      dockerfile: Dockerfile
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq/
    ports:
      - "8080:8080"
    networks:
      - crypto-network
    depends_on:
      rabbitmq:
        condition: service_healthy

  logs-consumer:
    build:
      context: logs-consumer
      dockerfile: Dockerfile
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
    networks:
      - crypto-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      crypto-app:
        condition: service_started

networks:
  crypto-network:
    driver: bridge