version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - crypto-network

  crypto-app:
    build:
      context: crypto-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - crypto-network
    depends_on:
      - rabbitmq

  logs-consumer:
    build:
      context: logs-consumer
      dockerfile: Dockerfile
    networks:
      - crypto-network
    depends_on:
      - rabbitmq
      - crypto-app

networks:
  crypto-network:
    driver: bridge